'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RegisterPage

	'''<summary>
	'''userExistsError control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents userExistsError As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''Label2 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''firstNameTB control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents firstNameTB As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''firstNameValidator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents firstNameValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''Label3 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label3 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''lastNameTB control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lastNameTB As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''lastNameValidator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents lastNameValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''Label4 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label4 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''addressOneTB control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents addressOneTB As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''address1Validator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents address1Validator As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''Label5 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label5 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''addressTwoTB control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents addressTwoTB As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''address2Validator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents address2Validator As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''Label6 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label6 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''cityTB control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cityTB As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''cityValidator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cityValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''Label7 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label7 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''stateTB control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents stateTB As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''stateValidator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents stateValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''Label8 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label8 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''zipTB control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents zipTB As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''RequiredFieldValidator7 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents RequiredFieldValidator7 As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''validZipCodeFormat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents validZipCodeFormat As Global.System.Web.UI.WebControls.RegularExpressionValidator

	'''<summary>
	'''Label9 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label9 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''phoneTB control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents phoneTB As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''phoneNumberReqValidator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents phoneNumberReqValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''validPhoneNumberFormat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents validPhoneNumberFormat As Global.System.Web.UI.WebControls.RegularExpressionValidator

	'''<summary>
	'''Label10 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label10 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''emailTB control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents emailTB As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''emailReqValidator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents emailReqValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''validEmailFormat control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents validEmailFormat As Global.System.Web.UI.WebControls.RegularExpressionValidator

	'''<summary>
	'''Label11 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label11 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''userNameTB control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents userNameTB As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''userNameValidator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents userNameValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''Label13 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label13 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''userPasswordTB control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents userPasswordTB As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''passwordValidator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents passwordValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''confirmPasswordLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents confirmPasswordLabel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''confirmPasswordTB0 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents confirmPasswordTB0 As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''confirmValidator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents confirmValidator As Global.System.Web.UI.WebControls.RequiredFieldValidator

	'''<summary>
	'''comparePasswordValidator control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents comparePasswordValidator As Global.System.Web.UI.WebControls.CompareValidator

	'''<summary>
	'''Label12 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Label12 As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''HyperLink1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents HyperLink1 As Global.System.Web.UI.WebControls.HyperLink

	'''<summary>
	'''agreeCB control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents agreeCB As Global.System.Web.UI.WebControls.CheckBox

	'''<summary>
	'''submitBTN control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents submitBTN As Global.System.Web.UI.WebControls.Button
End Class
