'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AddEdit

	'''<summary>
	'''addedLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents addedLabel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''coral control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents coral As Global.System.Web.UI.WebControls.Repeater

	'''<summary>
	'''addButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents addButton As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''updateButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents updateButton As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''editButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents editButton As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''deleteButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents deleteButton As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''resetButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents resetButton As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''cancelButton control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cancelButton As Global.System.Web.UI.WebControls.Button
End Class
