'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CustomComplexDataBasePage3

    '''<summary>
    '''coralCnameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coralCnameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NameTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NameTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''stallNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents stallNameLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dataTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dataTypeLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''fieldnameLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldnameLabel1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''categoryTB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents categoryTB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dataTypeDropDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dataTypeDropDown As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''categoryTB2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents categoryTB2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dataTypeDropDown2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dataTypeDropDown2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''fieldnameLabel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldnameLabel5 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''categoryTB3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents categoryTB3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dataTypeDropDown3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dataTypeDropDown3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''fieldnameLabel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fieldnameLabel4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''categoryTB4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents categoryTB4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dataTypeDropDown4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dataTypeDropDown4 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''categoryTB5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents categoryTB5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dataTypeDropDown5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dataTypeDropDown5 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''categoryTB6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents categoryTB6 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dataTypeDropDown6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dataTypeDropDown6 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''categoryTB7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents categoryTB7 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dataTypeDropDown7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dataTypeDropDown7 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''categoryTB8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents categoryTB8 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dataTypeDropDown8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dataTypeDropDown8 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''categoryTB9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents categoryTB9 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dataTypeDropDown9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dataTypeDropDown9 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''categoryTB10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents categoryTB10 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dataTypeDropDown10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dataTypeDropDown10 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''categoryTB11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents categoryTB11 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dataTypeDropDown11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dataTypeDropDown11 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Submit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cancelBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cancelBtn As Global.System.Web.UI.WebControls.Button
End Class
