'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CustomComplexDataBasePage0

    '''<summary>
    '''coralCnameLabel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coralCnameLabel1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''coralCnameLabel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coralCnameLabel2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''coralCnameLabel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents coralCnameLabel3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''userDatabasesDD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents userDatabasesDD As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SubmitBTN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SubmitBTN As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BTN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN As Global.System.Web.UI.WebControls.Button
End Class
