'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Query

	'''<summary>
	'''welcomeLbl control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents welcomeLbl As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''searchByLbl control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents searchByLbl As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''fieldDropDown control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents fieldDropDown As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''thatLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents thatLabel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''limitDropDown control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents limitDropDown As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''searchTB control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents searchTB As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''searchResults control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents searchResults As Global.System.Web.UI.WebControls.GridView

	'''<summary>
	'''SubmitBTN control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SubmitBTN As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''Cancel1 control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Cancel1 As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''NewSearchBTN control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents NewSearchBTN As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''Cancel2BTN control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents Cancel2BTN As Global.System.Web.UI.WebControls.Button
End Class
