'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CustomDataBase

	'''<summary>
	'''titleLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents titleLabel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''instructionsDiv control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents instructionsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

	'''<summary>
	'''coralCnameLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents coralCnameLabel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''NameTB control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents NameTB As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''stallNameLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents stallNameLabel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''categoryTB control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents categoryTB As Global.System.Web.UI.WebControls.TextBox

	'''<summary>
	'''anotherLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents anotherLabel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''YesBTN control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents YesBTN As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''NoBTN control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents NoBTN As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''dataTypeLabel control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dataTypeLabel As Global.System.Web.UI.WebControls.Label

	'''<summary>
	'''dataTypeDropDown control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents dataTypeDropDown As Global.System.Web.UI.WebControls.DropDownList

	'''<summary>
	'''SubmitNameBTN control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents SubmitNameBTN As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''submitCategoryBTN control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents submitCategoryBTN As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''submitCategory2BTN control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents submitCategory2BTN As Global.System.Web.UI.WebControls.Button

	'''<summary>
	'''cancelBtn control.
	'''</summary>
	'''<remarks>
	'''Auto-generated field.
	'''To modify move field declaration from designer file to code-behind file.
	'''</remarks>
	Protected WithEvents cancelBtn As Global.System.Web.UI.WebControls.Button
End Class
